{
 "title": "Space Environment",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Time", "type": "grafana-clock-panel", "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 } },
  { "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 } },
  {
   "title": "Air Measurements",
   "type": "graph",
   "description": "From CCS811. Code here: https://github.com/stigtsp/esp8266-environment-monitor",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ppm" }
   ],
   "targets": [
    {
     "alias": "CO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eCO2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "hackeriet/environment/eCO2" }
     ]
    },
    {
     "alias": "tVOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tVOC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "hackeriet/environment/tVOC" }
     ]
    }
   ]
  },
  {
   "title": "eCO2",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 16, "y": 4 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "alias": "eCO2",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eCO2",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "tVOC",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 4 },
   "format": "ppm",
   "valueName": "current",
   "targets": [
    {
     "alias": "tVOC",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "tVOC",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Space Temperature  (TODO: calibration)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 16, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "Temperature",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "hackeriet/environment/temp" }
     ]
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "singlestat",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 13 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "alias": "temp",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "temperature",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "topic", "operator": "=", "value": "hackeriet/environment/temp" }
     ]
    }
   ]
  }
 ]
}